### ISSUE TITLE
0.5.2 status text compatibility problem

### ISSUE THREAD

**Issue by fireattack** [jasadams/imagezoom#1]
Just copied from AMO, by circcc:

0.5.2 status text feature have problem with status text addons like Status-4-Evar, Status Box. Once image zoom status text is displayed, it is not disappear. Please make status text turn off option or fix it. Thanks. (FF20/WinXP)

I can confirm this problem in Fx21. win7.

**Comment by PeterDoubt** [comment]
Just to confirm same problem here.

Win Vista, FF20.0.1

**Comment by jasadams** [comment]
Added an option in 0.5.3 to disable statusbar display for imagezoom. The option is "imagezoom.showStatus" and is available only in about:config. Will disable by default and add an option to the preference pane in a future version.

**Comment by jasadams** [comment]
changing of defaults and a status display option has been checked into development branch. Due for release 0.6
