### ISSUE TITLE
Versions 0.5.2+ Missing "Scroll Mode" Option

### ISSUE THREAD

**Issue by MegaJar** [jasadams/imagezoom#3]
From version 0.5.2 and up, the options dialog is missing the "Scroll Mode" dropdown. Now all zooming is automatically in "Relative" mode, with no way to change it to "Absolute". Please put this option back in.

**Comment by jasadams** [comment]
Added back in 0.5.4

**Comment by MegaJar** [comment]
Great, thanks for the quick response!
