### ISSUE TITLE
0.5.4 on 64-bit Firefox variants needs 2 right-clicks to access right-click menu

### ISSUE THREAD

**Issue by irvinm** [jasadams/imagezoom#6]
I love your extension, but this problem has prevented me from moving to one of the 64-bit variants for quite some time so I thought I would report it.

Steps to reproduce:
1. Install 64-bit variant.  I'm currently trying "Cyberfox" (20.0.1), but have seen this with both "Pale Moon" and "Waterfox" in the past.
2. Find any graphic on a website, right-click and confirm right-click menu comes up.
3. Install 0.5.4 of imagezoom.
4. Find same graphic and see that the 1st right-click is ignored and the 2nd time it works fine.
5. Repeat as needed.  Each time, the 1st right-click is ignored.

Any ideas or suggestions?  I would be willing to help out however I can.

Sincerely,
Mike

**Comment by jasadams** [comment]
Fix committed to the development branch. As this is not a mainstream problem, I have scheduled it to be released with 0.6 (about a month away).
