### ISSUE TITLE
conflict with Status-4-evar (sort of ?) monopolization of the status bar

### ISSUE THREAD

**Issue by roger21** [jasadams/imagezoom#7]
hey,

image zoom keep putting info -- about i realy don't know witch image, even when you never asked him anything -- in the status bar
![clipboard-00](https://f.cloud.github.com/assets/892186/445792/44f96718-b1c5-11e2-99c8-ba90b08cea37.png)

it doesn't seem to overwrite other infos but it come back evry time there's nothing to display in the status bar

**Comment by jasadams** [comment]
See [Issue #1](https://github.com/jasadams/imagezoom/issues/1)
