### ISSUE TITLE
Unexpected Rapid Zooming

### ISSUE THREAD

**Issue by peterallcdn** [jasadams/imagezoom#8]
Image zooming behaviour changes randomly.

Sometimes the image zooms as expected, with each step of the scroll wheel the image zooms a small amount.

Other times, the image zooms unexpectedly, where the image zooms quickly and zooms too far not respecting the steps of the scroll wheel. So with just a small move of the mouse wheel, an image can go from a small size to overflowing the screen. This makes it very hard to actually zoom to a desired size.

I've been using ImageZoom for a long time, and this behaviour has only started recently I believe... in the past couple months I'd say.

I'm running the latest version of firefox on Windows 8 and am using a Logitech Performance MX mouse.

Thanks for any help,
Peter

**Comment by jasadams** [comment]
Do you observe this behaviour consistently with the same image or can the behaviour be different with exactly the same image. I had observed this behaviour recently during testing but it was consistent and since I fixed the code I have not observed it. I will probably need your help to narrow down the scenarios under which this occurs as I cannot fix the issue if I cannot recreate it.

**Comment by peterallcdn** [comment]
Thanks for the quick reply. I was going to do some testing to answer your questions and thought I should disable all my plugins first to make sure they didn't interfere... and, the zooming problem seems to have disappeared. I'm guessing there's a plugin conflict. I'll now enable them one by one and hopefully spot which plugin causes the problem with ImageZoom...

**Comment by peterallcdn** [comment]
I didn't even know I had this plugin installed, but I should have known it'd be the problem the moment I saw it... Logitech SetPoint 6.5 "Smooth scrolling for Logitech mice."

Once the above plugin has been disabled, ImageZoom works as expected.

**Comment by jasadams** [comment]
I will close this issue as I don't plan on doing anything to address the conflict with that plugin. thanks for reporting
